### ISSUE TITLE
Main thread call

### ISSUE THREAD

**Issue by x1p** [Blackixx/BossShopPro#16]
First of all. I love your plugin. Hope it will be continued. There no shop like BossShopPro.

I was experimenting with a program to investigate plugins on the main thread.
BSP appears to call the main thread on load. I'm sure it's a minor thing and hope you can take advantage of this to improve ;-)

```
[10:33:53] [Server thread/WARN]: [TruAntiLag] Main thread call, Bad!: https://api.spigotmc.org/legacy/premium.php?user_id=566677&resource_id=25699&nonce=544981023
[10:33:53] [Server thread/WARN]: [TruAntiLag] Please notify the developer! https://git.io/vA9m2
[10:33:53] [Server thread/ERROR]: Error occurred while enabling BossShopPro v2.0.5 (Is it up to date?)
java.lang.RuntimeException: No touchy touchy my main thready
	at net.poweredbyhate.truantilag.BadDetector.select(BadDetector.kt:17) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_212]
	at org.black_ixx.bossshop.BossShop.loadConfig0(BossShop.java) ~[?:?]
	at org.black_ixx.bossshop.BossShop.onEnable(BossShop.java) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-630]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-630]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-630]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Links in the log:
https://api.spigotmc.org/legacy/premium.php?user_id=566677&resource_id=25699&nonce=544981023 (makes no sense to me)
https://git.io/vA9m2 (points to https://github.com/aikar/TaskChain/wiki/Why-TaskChain)

Tested with BossShopPro 2.0.5
Paper 1.13.2 build 630

**Comment by Logende** [comment]
https://www.spigotmc.org/wiki/bossshoppro-faq-and-help/ -> "My players are able to take items out of the GUI": DId you check this out already?
