### ISSUE TITLE
 BossShopPro version 1.14

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Blackixx/BossShopPro#8]
**Hello, I do not know if you are working for version 1.14. But since I have not seen any information about it, I mention the following error.**

**When starting the server with the git-Spigot-1eece4f-d5c2e3c version (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT**

[BossShopPro] Plugin BossShopPro v2.0.3 generated an exception while executing task 71
java.lang.IllegalStateException: BSRegisterTypesEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.black_ixx.bossshop.managers.ClassManager.setupDependentClasses(ClassManager.java:123) ~[?:?]
	at org.black_ixx.bossshop.BossShop$1.run(BossShop.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**When stopping the server**

Error occurred while disabling BossShopPro v2.0.3 (Is it up to date?)
java.lang.NullPointerException: null
	at org.black_ixx.bossshop.BossShop.unloadClasses(BossShop.java:171) ~[?:?]
	at org.black_ixx.bossshop.BossShop.onDisable(BossShop.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:429) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:392) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:673) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:695) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:839) [spigot.jar:git-Spigot-1eece4f-d5c2e3c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**The plugin does not work, when writing / shop it does not do anything, and it does not show an error.**

**Thanks and best regards**

**Comment by Mundo-Minecraft** [comment]
[BossShopPro] Plugin BossShopPro v2.0.3 generated an exception while executing task 81
java.lang.IllegalStateException: BSRegisterTypesEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-1eece4f-68e72f6]
	at org.black_ixx.bossshop.managers.ClassManager.setupDependentClasses(ClassManager.java:123) ~[?:?]
	at org.black_ixx.bossshop.BossShop$1.run(BossShop.java:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-1eece4f-68e72f6]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-1eece4f-68e72f6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Mundo-Minecraft** [comment]
solved in the last released version, thanks
